#!/bin/bash
SOURCE_NIX="source $ENVSDIR/.nix-profile/etc/profile.d/nix.sh"
${SOURCE_NIX}
rsync -a $HOME_TEMPLATE/ $HOME
grep -q -F "${SOURCE_NIX}" $HOME/.bashrc || printf "\n$SOURCE_NIX\n" >> $HOME/.bashrc
PS1_MOD="export PS1=${PS1}(DevContainer)\$\w"
${PS1_MOD}
grep -q -F "${PS1_MOD}" $HOME/.bashrc || printf "\n$PS1_MOD\n" >> $HOME/.bashrc
touch $HOME/.stignore && \
grep -q -F '#include .home_sync_ignore' $HOME/.stignore || echo '#include .home_sync_ignore' >> $HOME/.stignore

# A temporary fix: need a more Nix way to do this, e.g. in postBuild hook:
SET_IDEA_JDK="export IDEA_JDK=/usr/lib/jvm/zulu-8-amd64"
grep -q -F "${SET_IDEA_JDK}" $HOME/.bashrc || printf "\n$SET_IDEA_JDK\n" >> $HOME/.bashrc

syncthing -gui-address 0.0.0.0:8384 &
tmux
