#!/bin/bash
SOURCE_NIX="source $ENVSDIR/.nix-profile/etc/profile.d/nix.sh"
${SOURCE_NIX}
rsync -a $HOME_TEMPLATE/ $HOME
grep -q -F "${SOURCE_NIX}" $HOME/.bashrc || printf "\n$SOURCE_NIX\n" >> $HOME/.bashrc
PS1_MOD="export PS1=${PS1}(DevContainer)\$\w"
${PS1_MOD}
grep -q -F "${PS1_MOD}" $HOME/.bashrc || printf "\n$PS1_MOD\n" >> $HOME/.bashrc
touch $HOME/.stignore && \
grep -q -F '#include .home_sync_ignore' $HOME/.stignore || echo '#include .home_sync_ignore' >> $HOME/.stignore

SET_DYNAMIC_ENV="source $HOME/workspace/docker-nix-intellij/nix-env-dynamic.sh"
${SET_DYNAMIC_ENV}
grep -q -F "${SET_DYNAMIC_ENV}" $HOME/.bashrc || printf "\n$SET_DYNAMIC_ENV\n" >> $HOME/.bashrc

touch /tmp/syncthing.log
mv -b /tmp/syncthing.log /tmp/syncthing.log.1
syncthing -gui-address 0.0.0.0:8384 2>&1 > /tmp/syncthing.log &
emacs -nw
