#!/bin/bash
SOURCE_NIX="source $ENVSDIR/.nix-profile/etc/profile.d/nix.sh"
${SOURCE_NIX}
rsync -a $HOME_TEMPLATE/ $HOME
grep -q -F "${SOURCE_NIX}" $HOME/.bashrc || printf $SOURCE_NIX >> $HOME/.bashrc
PS1_MOD="\nexport PS1=\"${PS1}(DevContainer)$\"\n"
grep -q -F "${PS1_MOD}" $HOME/.bashrc || printf $PS1_MOD >> $HOME/.bashrc
touch $HOME/.stignore && \
grep -q -F '#include .home_sync_ignore' $HOME/.stignore || echo '#include .home_sync_ignore' >> $HOME/.stignore
syncthing -gui-address 0.0.0.0:8384 &
/bin/bash
